/// Flutter icons PokedexIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  PokedexIcons
///      fonts:
///       - asset: fonts/PokedexIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class PokedexIcons {
  PokedexIcons._();

  static const _kFontFam = 'PokedexIcons';

  static const IconData ic_ball = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData ic_item = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData ic_pikachu = const IconData(0xe802, fontFamily: _kFontFam);
}
